import re


def make_monitor_name(ean: str | None, title: str) -> str:
    if ean:
        return f"ftp_{ean}"
    slug = re.sub(r"[^a-z0-9]+", "_", title.lower()).strip("_")[:40]
    return f"ftp_{slug}"


def render_monitor(
    name: str,
    product_name: str,
    ean: str | None,
    currency: str,
    schedule: str,
    notify_channels: list[str],
) -> str:
    query = ean if ean else product_name
    return f'''# Auto-generated by findThatProduct — do not edit manually
_PRODUCT_NAME = {repr(product_name)}
_EAN = {repr(ean or "")}
_CURRENCY = {repr(currency)}
_QUERY = {repr(query)}

import os as _os
import json as _json
from app.helpers import Monitor, set_value, record_metric

_FTP_URL = _os.getenv("FTP_INTERNAL_URL", "http://findthatproduct.findthatproduct.svc.cluster.local")

monitor = Monitor(
    name={repr(name)},
    schedule={repr(schedule)},
    notify_channels={repr(notify_channels)},
    metric="product_price",
)


@monitor.check
async def check(page, ctx):
    response = await page.request.post(
        f"{{_FTP_URL}}/api/search",
        data=_json.dumps({{"query": _QUERY}}),
        headers={{"Content-Type": "application/json"}},
    )
    data = await response.json()

    results = [r for r in data.get("results", []) if r.get("price") is not None]
    if not results:
        return

    best = min(results, key=lambda r: r["price"])
    price = round(best["price"], 2)

    await set_value(ctx.db, ctx.monitor_name, str(price))

    if ctx.influx:
        await record_metric(
            ctx.influx,
            "product_price",
            price,
            monitor=ctx.monitor_name,
            source=best["source"],
        )
'''
