import re


def make_monitor_name(ean: str | None, title: str) -> str:
    if ean:
        return f"ftp_{ean}"
    slug = re.sub(r"[^a-z0-9]+", "_", title.lower()).strip("_")[:40]
    return f"ftp_{slug}"


def render_monitor(
    name: str,
    product_name: str,
    ean: str | None,
    currency: str,
    schedule: str,
    notify_channels: list[str],
) -> str:
    query = ean if ean else product_name
    return f'''# Auto-generated by findThatProduct — do not edit manually
_PRODUCT_NAME = {repr(product_name)}
_EAN = {repr(ean or "")}
_CURRENCY = {repr(currency)}
_QUERY = {repr(query)}

import os as _os
import json as _json
from app.helpers import Monitor, get_last_value, set_value, notify, record_metric

_FTP_URL = _os.getenv("FTP_INTERNAL_URL", "http://findthatproduct.findthatproduct.svc.cluster.local")

monitor = Monitor(
    name={repr(name)},
    schedule={repr(schedule)},
    notify_channels={repr(notify_channels)},
    metric={repr(name)},
    tags=["findthatproduct"],
)


@monitor.check
async def check(page, ctx):
    response = await page.request.post(
        f"{{_FTP_URL}}/api/search",
        data=_json.dumps({{"query": _QUERY}}),
        headers={{"Content-Type": "application/json"}},
    )
    data = await response.json()

    results = [r for r in data.get("results", []) if r.get("price") is not None]
    if not results:
        return

    prices = sorted(r["price"] for r in results)
    median = prices[len(prices) // 2]
    plausible = [r for r in results if r["price"] >= median * 0.5] or results
    best = min(plausible, key=lambda r: r["price"])
    price = round(best["price"], 2)
    price_str = f"€{{price:.2f}}".replace(".", ",")

    prev = await get_last_value(ctx.db, ctx.monitor_name)
    await set_value(ctx.db, ctx.monitor_name, price_str)
    ctx.logger.info("%s: %s via %s", _PRODUCT_NAME, price_str, best["source"])

    if prev is not None and price_str != prev and ctx.apprise:
        await notify(ctx.apprise, title=f"{{_PRODUCT_NAME}} price changed", body=price_str, tags={repr(notify_channels)})

    if ctx.influx:
        await record_metric(
            ctx.influx,
            ctx.monitor_name,
            price,
            source=best["source"],
        )
'''
